using System.Collections.Generic;
using UnityEngine;

namespace CardsChaos.Cards
{
    [CreateAssetMenu(menuName = "CardsChaos/Card Set", fileName = "CardSet")]
    public class CardSetDefinition : ScriptableObject
    {
        [Tooltip("Folder name of the set. The stable key everything else refers to - the save " +
                 "included - so it is never shown to the player.")]
        [SerializeField] private string setId;

        [Tooltip("What the player reads on the album's set button. Generated by " +
                 "Tools/Cards/Build Set Names, which is a separate pass from Build All Card Sets " +
                 "so that hand-corrected names survive a rebuild.")]
        [SerializeField] private string setName;

        [SerializeField] private Sprite icon;
        [SerializeField] private Sprite iconInnerShadow;

        [SerializeField] private List<GameObject> cards = new List<GameObject>();

        // NonSerialized for the same reason as in CardCatalog: Unity serializes private
        // serializable fields across domain reloads, so a cache built in edit mode would
        // otherwise leak into play mode.
        [System.NonSerialized] private Dictionary<int, CardIdentity> _byNumber;

        public string SetId => setId;

        /// <summary>
        /// Falls back to the id so a set that has not been through the naming pass still shows
        /// something readable rather than an empty button.
        /// </summary>
        public string SetName => string.IsNullOrEmpty(setName) ? setId : setName;

        public Sprite Icon => icon;
        public Sprite IconInnerShadow => iconInnerShadow;

        public IReadOnlyList<GameObject> Cards => cards;

        /// <summary>How many cards make a complete set - the Y of the album's "X / Y".</summary>
        public int CardCount => cards.Count;

        /// <summary>
        /// The card that belongs at a given number. Numbers run 1..<see cref="CardCount"/>; the
        /// builder rejects a set whose numbering has holes, because the album lays slots out by
        /// number and a hole would leave a slot no card could ever fill.
        /// </summary>
        public bool TryGetCard(int number, out CardIdentity identity)
        {
            return ByNumber.TryGetValue(number, out identity);
        }

        private Dictionary<int, CardIdentity> ByNumber => _byNumber ??= BuildLookup();

        private void OnDisable() => _byNumber = null;

        private Dictionary<int, CardIdentity> BuildLookup()
        {
            var lookup = new Dictionary<int, CardIdentity>(cards.Count);

            foreach (GameObject prefab in cards)
            {
                if (prefab == null)
                {
                    Debug.LogError($"[CardSetDefinition] Set '{setId}' contains a broken card reference.", this);
                    continue;
                }

                // Resolved through the prefab root rather than stored as a component reference:
                // component references into prefab variants do not survive deserialization at
                // runtime, which is why the serialized list holds GameObjects.
                if (!prefab.TryGetComponent(out CardIdentity identity))
                {
                    Debug.LogError($"[CardSetDefinition] '{prefab.name}' has no {nameof(CardIdentity)}.", prefab);
                    continue;
                }

                if (!lookup.TryAdd(identity.Number, identity))
                {
                    Debug.LogError(
                        $"[CardSetDefinition] Set '{setId}' has two cards numbered " +
                        $"{identity.Number}; '{prefab.name}' is the duplicate.", prefab);
                }
            }

            return lookup;
        }
    }
}
